In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('files/Vinson_Datos_2019_2024-R1-N.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34973 entries, 0 to 34972
Columns: 212 entries, folio to ponderacion
dtypes: float64(212)
memory usage: 56.6 MB

In [6]:
df

,folio,SbjNum,RUID,nse_nue,ciudad,ecat,edadx,sexo,medicion_Q,anio,...,img_48_6,img_49_6,b2f.r12,leales,switcher,potencial,esporadico,no_interesados,abandonador,ponderacion
0,9.532920e+07,95329205.0,2.998823e+09,2.0,1.0,4.0,27.0,1.0,27.0,19.0,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.625511
1,9.532921e+07,95329208.0,2.998823e+09,2.0,1.0,2.0,18.0,1.0,27.0,19.0,...,NaN,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,1.625511
2,9.536568e+07,95365679.0,3.022316e+09,3.0,1.0,9.0,54.0,1.0,27.0,19.0,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.636603
3,9.536568e+07,95365681.0,3.022316e+09,2.0,1.0,3.0,24.0,1.0,27.0,19.0,...,NaN,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,1.625511
4,9.536568e+07,95365683.0,3.022316e+09,2.0,1.0,5.0,33.0,2.0,27.0,19.0,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.625511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34968,2.895142e+10,NaN,2.895142e+10,3.0,2.0,3.0,22.0,1.0,27.0,19.0,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,0.802382
34969,2.895142e+10,NaN,2.895142e+10,3.0,2.0,8.0,45.0,1.0,27.0,19.0,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,0.802382
34970,2.895142e+10,NaN,2.895142e+10,3.0,2.0,2.0,19.0,2.0,27.0,19.0,...,NaN,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,0.802382
34971,2.895142e+10,NaN,2.895142e+10,3.0,2.0,2.0,16.0,1.0,27.0,19.0,...,NaN,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,0.802382
34972,2.895142e+10,NaN,2.895142e+10,2.0,2.0,5.0,34.0,1.0,27.0,19.0,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,0.793456